name: Sync docs from repos B and C

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo A (testing branch)
        uses: actions/checkout@v3
        with:
          ref: testing
          token: ${{ secrets.PAT_TOKEN }}

      - name: Clone repo B
        run: git clone --depth 1 https://github.com/Kamui-Kazi/Shoutout-Raid.git Shoutout-clone

      - name: Clone repo C
        run: git clone --depth 1 https://github.com/Kamui-Kazi/Redeem-Counter.git Redeem-clone

      - name: Replace docs from repos B and C
        run: |
          rm -rf ./Shoutout-Raid ./Redeem-Counter
          cp -r Shoutout-clone/docs/ ./Shoutout-Raid
          cp -r Redeem-clone/docs/* ./Redeem-Counter 

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Shoutout-Raid/
          git add Redeem-Counter/
          git diff --cached --quiet || git commit -m "Update docs from repos B and C"
          git push origin testing
