name: Sync docs

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo kamui-kazi.github.io (testing branch)
        uses: actions/checkout@v3
        with:
          ref: testing
          token: ${{ secrets.PAT_TOKEN }}

      - name: Clone Shoutout-Raid (Repo B)
        run: git clone --depth 1 https://github.com/Kamui-Kazi/Shoutout-Raid.git temp-b

      - name: Clone Redeem-Counter (Repo C)
        run: git clone --depth 1 https://github.com/Kamui-Kazi/Redeem-Counter.git temp-c

      - name: Copy docs folders into subdirectories
        run: |
          rm -rf Shoutout-Raid Redeem-Counter  # optional cleanup
          mkdir -p Shoutout-Raid Redeem-Counter

          # Use rsync to preserve structure and remove deleted files
          rsync -a --delete temp-b/docs/ Shoutout-Raid/
          rsync -a --delete temp-c/docs/ Redeem-Counter/

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Shoutout-Raid/ Redeem-Counter/
          git diff --cached --quiet || git commit -m "Sync docs from Shoutout-Raid and Redeem-Counter"
          git push origin testing
